name: Deploy App CI

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11   
           
      - name: Grant rights
        run: chmod +x build.gradle
      
      - name: Copy google-services.json
        run: echo ${{ secrets.GOOGLE_JSON }} | base64 --decode > app/google-services.json
      
      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease
    
      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
            releaseDirectory: app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.KEY_STORE }}
            alias: ${{ secrets.KEY_ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: app/build/outputs/bundle/release/app-release.aab
            
      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
      
      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJson: service_account.json
            packageName: com.egoriku.belarusresistanceflag
            releaseFile: app/build/outputs/bundle/release/app-release.aab
            track: beta
            whatsNewDirectory: whatsnew/
